import java.util.*;
import java.io.*;
import javax.swing.JOptionPane;
/**
 * Clave: 143743
 * @author Bernardo Mondragon Brozon
 */
public class frmComida extends javax.swing.JFrame {

    public final int DIM = 50;
    public final int MAX = 100;
    public int zanahorias[];
    public int cajas, quiereComer;
    
    public void leeInfo(String nombre){
        File datos;
        Scanner lee;
        datos = new File(nombre + ".txt");
        zanahorias = new int[DIM];
        cajas = 0;
        int hay;
        hay = 0;
        try{
        lee = new Scanner(datos);
        }
        catch(Exception e){
            lee = null;
        }
        if (lee != null){
            this.quiereComer = lee.nextInt();
            while(lee.hasNextInt() && cajas < DIM){
                zanahorias[cajas] = Math.min(100, lee.nextInt());
                hay = hay + zanahorias[cajas];
                cajas = cajas + 1;
            }
            lee.close();
            this.quiereComer = Math.min(hay, quiereComer);
        }
        
    }
    
    public frmComida() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.txtTitulo.setEditable(false);
        this.cmbComensales.setSelectedIndex(-1);
    }

    public int cajaMasZanahorias(){
        int i, max;
        max = 0;
        for (i = 1; i < cajas ; i++)
            if( zanahorias[i] > zanahorias[max])
                max = i;
        return max;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JTextField();
        cmbComensales = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnComer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaIniciales = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFinales = new javax.swing.JTextArea();
        lblRespuesta = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zanahorias");

        txtTitulo.setBackground(new java.awt.Color(102, 255, 102));
        txtTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 255));
        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitulo.setText("Cajas de zanahorias");
        txtTitulo.setCaretColor(new java.awt.Color(153, 255, 102));

        cmbComensales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hanajo", "Masiosare", "Pepito", "Teofilo", "zeferina" }));

        jLabel1.setText("Comensales");

        btnComer.setText("Comer");
        btnComer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComerActionPerformed(evt);
            }
        });

        jLabel2.setText("Cajas iniciales:");

        jLabel3.setText("Cajas finales:");

        txtaIniciales.setColumns(20);
        txtaIniciales.setRows(5);
        jScrollPane1.setViewportView(txtaIniciales);

        txtFinales.setColumns(20);
        txtFinales.setRows(5);
        jScrollPane2.setViewportView(txtFinales);

        lblRespuesta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRespuesta.setText("  ");

        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbComensales, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComer)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTerminar)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbComensales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(40, 40, 40)
                .addComponent(lblRespuesta)
                .addGap(18, 18, 18)
                .addComponent(btnTerminar)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComerActionPerformed
        String iniciales;
        int i, loc;
        iniciales = "";
        loc = 0;
        if (this.cmbComensales.getSelectedIndex() != -1){
            leeInfo(this.cmbComensales.getSelectedItem().toString());
            for (i = 0; i < cajas; i++)
                iniciales = iniciales + i + " - " + zanahorias[i] + "\n";
            this.txtaIniciales.setText(iniciales);
            for( i = quiereComer; i > 0; i--){
                loc  = this.cajaMasZanahorias();
                zanahorias[loc] = zanahorias[loc] - 1;
            }
            iniciales = "";
            for (i = 0; i < cajas; i++) {
                iniciales = iniciales + i + " - " + zanahorias[i] + "\n";
            }
            this.txtFinales.setText(iniciales);
            this.lblRespuesta.setText("Comió " + quiereComer + " zanahorias y ultima de la caja " + loc);
        }
        else
            JOptionPane.showMessageDialog(null, "Seleccione un comensal por favor"
                    + "\n\nsi no desea comer haga clic en Terminar");
        
    }//GEN-LAST:event_btnComerActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmComida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComer;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JComboBox<String> cmbComensales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JTextArea txtFinales;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextArea txtaIniciales;
    // End of variables declaration//GEN-END:variables
}
